// GENERATED BY go generate; DO NOT EDIT.

package http

// Changed from Discordo's const to a var so the running CLI can refresh it from
// Discord's login page instead of shipping a number that goes stale.
var ClientBuildNumber = 584177
